---
fixtures:
  repositories:
    augeasproviders :
      repo: "https://github.com/simp/augeasproviders"
      branch: "simp-master"
    augeasproviders_core :
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_sysctl:
      repo: "https://github.com/simp/augeasproviders_sysctl"
      branch: "simp-master"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
  symlinks:
    sysctl: "#{source_dir}"
